In [1]:
import re

def get_input_by_lines(prob):
    lines = []

    with open('prob{}.txt'.format(prob), 'r') as prob_input:
        for line in prob_input:
            line = re.sub(r'\t', ',', line)
            lines.append(line.strip())
    #print(lines[:4], len(lines))

    return lines

#1

In [2]:
def get_repeat_sum(num):
    numlist = str(num) + str(num)[0]
    sum_ = 0
    for idx, digit in enumerate(numlist[:-1]):
        sum_ += int(digit == numlist[idx+1])*int(digit)
    return sum_

In [3]:
def get_repeat_sum2(num):
    numlen = len(num)
    assert not numlen & 1
    
    numlist = str(num) + str(num)[0]
    
    sum_ = 0
    for idx, digit in enumerate(numlist[:-1]):
        goal = (idx+numlen//2) % numlen
        sum_ += int(digit == numlist[goal])*int(digit)
    
    return sum_

In [12]:
ex1 = ','.join(get_input_by_lines(1))

In [13]:
len(ex1)

2166

In [14]:
get_repeat_sum(ex1)

1097

In [15]:
get_repeat_sum2(ex1)

1188

#2

In [26]:
ex2_0 = get_input_by_lines(2)
ex2 = np.array([x.split(',') for x in ex2_0]).astype(np.int32)

In [28]:
import numpy as np
import re


def listrange(mylist):
    mylist = sorted(mylist)
    return mylist[-1] - mylist[0]

def listdiv(mylist):
    mylist = np.array(sorted(mylist))
    thresh = mylist[-1] // 2
    
    idx = 0
    while mylist[idx] <= thresh:
        filtlist = mylist[mylist/mylist[idx] == mylist//mylist[idx]]
        if len(filtlist) > 1:
            val = filtlist[-1] / mylist[idx]
            break
        idx += 1
    
    return val

print(np.apply_along_axis(listrange, axis=1, arr=ex2).sum())
print(np.apply_along_axis(listdiv, axis=1, arr=ex2).sum())

50376
267.0


#3

In [1]:
# part 2


#4

In [34]:
ex4_0 = get_input_by_lines(4)
ex4 = np.array([x.split(' ') for x in ex4_0])

In [36]:
import re
from itertools import combinations
from functools import reduce

def solve41(inputlist):
    return sum([len(x) == len(set(x)) for x in inputlist])

def isanagram(str1, str2):
    return sorted(list(str1)) == sorted(list(str2))

def solve42(inputlist):
    return len(inputlist) - sum([reduce((lambda x, y: x or y),
                                [isanagram(*x) for x in combinations(elem, 2)])
                            for elem in inputlist])

In [37]:
solve41(ex4), solve42(ex4)

(325, 119)

#5 

In [60]:
ex5_0 = get_input_by_lines(5)
ex5 = [int(x) for x in ex5_0]

In [61]:
len(ex5)

1003

In [62]:
def solve51(input_list0):
    input_list = input_list0.copy()
    idx = 0
    count = 0
    errors = False

    while not errors:
        try:
            jump_val = input_list[idx]
            input_list[idx] += 1
            idx += jump_val
            count += 1
        except:
            print("last index {}".format(idx))
            errors = True
            continue
    print(count)

In [63]:
def solve52(input_list0):
    input_list = input_list0.copy()
    idx = 0
    count = 0
    errors = False

    while not errors:
        try:
            jump_val = input_list[idx]
            if input_list[idx] >= 3:
                input_list[idx] -= 1
            else:
                input_list[idx] += 1
            idx += jump_val
            count += 1
        except:
            print("last index {}".format(idx))
            errors = True
            continue
    print(count)

In [64]:
solve51(ex5)

last index 1003
315613


In [65]:
solve52(ex5)

last index 1003
22570529


#6

In [3]:
np.argmax([1, 6, 2, 6])

1

In [157]:
a = [11, 11, 13, 7, 0, 15, 5, 5, 4, 4, 1, 1, 7, 1, 15, 11]

In [159]:
def solve6(a):
    seen = []
    current = a
    
    count = 0
    
    while (current not in seen) and (count <= 2000000):
        #print('going with {} AND {}'.format(current, seen))
        seen.append(current.copy())
        idx = np.argmax(current)
        maxval = current[idx]
        current[idx] = 0

        while maxval > 0:
            idx = (idx + 1) % len(current)
            current[idx] += 1
            maxval -= 1
        
        count += 1
    
    idces = seen.index(current)
    print(idces)
    print(seen[(idces-1):(idces+2)])
    return count, seen, current



In [160]:
solve6(a)

1281
[[0, 15, 13, 13, 11, 11, 9, 9, 7, 7, 5, 5, 3, 2, 1, 0], [1, 0, 14, 14, 12, 12, 10, 10, 8, 8, 6, 6, 4, 3, 2, 1], [2, 0, 0, 15, 13, 13, 11, 11, 9, 9, 7, 7, 5, 4, 3, 2]]


(4074,
 [[11, 11, 13, 7, 0, 15, 5, 5, 4, 4, 1, 1, 7, 1, 15, 11],
  [12, 12, 14, 8, 1, 0, 6, 6, 5, 5, 2, 2, 8, 2, 16, 12],
  [13, 13, 15, 9, 2, 1, 7, 7, 6, 6, 3, 3, 9, 3, 1, 13],
  [14, 14, 0, 10, 3, 2, 8, 8, 7, 7, 4, 4, 10, 4, 2, 14],
  [0, 15, 1, 11, 4, 3, 9, 9, 8, 8, 5, 5, 11, 5, 3, 14],
  [1, 0, 2, 12, 5, 4, 10, 10, 9, 9, 6, 6, 12, 6, 4, 15],
  [2, 1, 3, 13, 6, 5, 11, 11, 10, 10, 7, 7, 13, 7, 5, 0],
  [3, 1, 3, 0, 7, 6, 12, 12, 11, 11, 8, 8, 14, 8, 6, 1],
  [4, 2, 4, 1, 8, 7, 13, 13, 12, 12, 9, 8, 0, 9, 7, 2],
  [5, 3, 5, 2, 8, 7, 0, 14, 13, 13, 10, 9, 1, 10, 8, 3],
  [6, 4, 6, 3, 9, 8, 0, 0, 14, 14, 11, 10, 2, 11, 9, 4],
  [7, 5, 7, 4, 10, 9, 1, 0, 0, 15, 12, 11, 3, 12, 10, 5],
  [8, 6, 8, 5, 11, 10, 2, 1, 1, 0, 13, 12, 4, 13, 11, 6],
  [9, 7, 9, 6, 12, 11, 3, 2, 1, 0, 0, 13, 5, 14, 12, 7],
  [10, 8, 10, 7, 13, 12, 4, 3, 2, 1, 1, 14, 5, 0, 13, 8],
  [11, 9, 11, 8, 14, 13, 5, 4, 3, 2, 1, 0, 6, 1, 14, 9],
  [12, 10, 12, 8, 0, 14, 6, 5, 4, 3, 2, 1, 7, 2, 15, 10],
  [13, 11, 13, 9, 1, 

In [161]:
4074 - 1281

2793

#7

In [68]:
ex6 = get_input_by_lines(6)

In [69]:
ex6

['wdysq (135) -> sxldvex, wiasj',
 'vjwuuft (33) -> inuci, neddz, rwamq',
 'oislgqy (77)',
 'lphki (233)',
 'wgbviwb (417)',
 'vikip (136) -> eofyk, dkexo, xzsxx',
 'elmieqh (19) -> dbziu, spefs, krtxpw',
 'tmzef (79)',
 'ectlgy (232) -> zmstcy, ncobxr',
 'sdatyo (91)',
 'uisri (11)',
 'smqimxg (132) -> husor, olzys',
 'pltzthr (82)',
 'szaqj (188) -> ptnndxj, fljpye',
 'jqdngi (58)',
 'uazwsu (15)',
 'xrrhso (79)',
 'gxeehd (68) -> iweii, rnqlzmv, hpmtom, vfzwqfr, xfzxrd, sgqhelx, hibjkps',
 'evkoenr (43) -> oecxbyt, qbthgst',
 'qivuzn (52)',
 'udeev (389) -> lphki, qthzk, hpgsb',
 'izgqzs (96) -> vbxzk, ubrrdtd',
 'naxtp (65)',
 'mvtkwn (42)',
 'sxldvex (34)',
 'tnlpmw (49)',
 'rzbrbmy (31) -> dvnqv, helyy',
 'esavxwq (81)',
 'yqgru (465) -> gfuyuz, elmieqh, xckzut, tmbhjxf',
 'ygypj (1303) -> ohcuki, ejdjxu, ytabct',
 'yggqq (855) -> gowlaq, ebtoxi, xpljwl',
 'ubaxya (92)',
 'pjkzokv (23)',
 'lvarp (76)',
 'yrysmsi (14)',
 'nofepy (23)',
 'apjeywv (132) -> kclmmu, exsugls',
 'licrtw

In [11]:
b

'fwft (72) -> ktlj, cntj, xhth'

In [81]:
def dictify(lines):
    name = re.search(r'\w+', lines).group(0)
    weight = int(re.search(r'\((\d+)\)', lines).group(1))
    children = re.search(r'-\> (.+)$', lines)
    if children:
        children = children.group(1).split(', ')
    return {'name': name, 'weight' : weight, 'children' : children}

def solve71(input_lines):
    input_dict = [dictify(x) for x in input_lines]

    result = []
    for item in input_dict:
        if item['children']:
            result.extend(item['children'])

    return set(x['name'] for x in input_dict) - set(result)

In [82]:
solve71(ex6)

{'vgzejbd'}

In [78]:
def dictify2(b):
    name = re.search(r'\w+', b).group(0)
    weight = int(re.search(r'\((\d+)\)', b).group(1))
    children = re.search(r'-\> (.+)$', b)
    if children:
        children = children.group(1).split(', ')
    return name, weight, children

def process7(a):
    resdict = {}
    
    for item in a:
        n, w, c = dictify2(item)
        resdict[n] = {'weight' : w, 'children' : c}
    
    return resdict

In [79]:
b4 = process7(ex6)

In [80]:
b4

{'wdysq': {'children': ['sxldvex', 'wiasj'], 'weight': 135},
 'vjwuuft': {'children': ['inuci', 'neddz', 'rwamq'], 'weight': 33},
 'oislgqy': {'children': None, 'weight': 77},
 'lphki': {'children': None, 'weight': 233},
 'wgbviwb': {'children': None, 'weight': 417},
 'vikip': {'children': ['eofyk', 'dkexo', 'xzsxx'], 'weight': 136},
 'elmieqh': {'children': ['dbziu', 'spefs', 'krtxpw'], 'weight': 19},
 'tmzef': {'children': None, 'weight': 79},
 'ectlgy': {'children': ['zmstcy', 'ncobxr'], 'weight': 232},
 'sdatyo': {'children': None, 'weight': 91},
 'uisri': {'children': None, 'weight': 11},
 'smqimxg': {'children': ['husor', 'olzys'], 'weight': 132},
 'pltzthr': {'children': None, 'weight': 82},
 'szaqj': {'children': ['ptnndxj', 'fljpye'], 'weight': 188},
 'jqdngi': {'children': None, 'weight': 58},
 'uazwsu': {'children': None, 'weight': 15},
 'xrrhso': {'children': None, 'weight': 79},
 'gxeehd': {'children': ['iweii',
   'rnqlzmv',
   'hpmtom',
   'vfzwqfr',
   'xfzxrd',
   'sgq

In [82]:
def get_weight(mainlist, name):
    if not mainlist[name]['children']:
        return mainlist[name]['weight']
    else:
        return mainlist[name]['weight'] + sum([get_weight(mainlist, child) for child in mainlist[name]['children']])

In [78]:
get_weight(b4, 'fwft')

243

In [88]:
def balanced(mainlist, name):
    if not mainlist[name]['children']:
        return True
    else:
        weights = [get_weight(mainlist, child) for child in mainlist[name]['children']]
        return weights.count(weights[0]) == len(weights), weights

In [90]:
balanced(b4, 'tknk')

(False, [251, 243, 243])

In [99]:
b4['fwft']['children'][2]

'xhth'

In [115]:
def where_to_go(mainlist, name):
    childlist = mainlist[name]['children']
    if not childlist:
        return None
    else:
        is_balanced, weights = balanced(mainlist, name)
        if is_balanced:
            return []
        elif len(weights) == 2:
            return childlist
        else:
            for idx, item in enumerate(weights):
                if weights.count(item) == 1:
                    return [childlist[weights.index(item)]]

In [144]:
solve7(a).pop()

'tknk'

In [137]:
where_to_go(b4, 'tknk')

['ugml']

In [138]:
where_to_go(b4, 'ugml')

[]

In [141]:
[get_weight(b4, c) for c in b4['ugml']['children']]

[61, 61, 61]

In [161]:
def find_wrong(a):
    base = solve7(a).pop()
    
    a3 = re.sub(r'\n', ';', a)[1:-1].split(';')
    mainlist = process7(a3)
    
    current_node = base
    parent_node = None
    end_found = False
    #print(mainlist, current_node)
    
    while not end_found:
        to_go = where_to_go(mainlist, current_node)
        
        if not to_go:
            end_found = True
        else:
            parent_node = current_node
            current_node = to_go[0]
            
    return parent_node, [get_weight(mainlist, c) for c in mainlist[parent_node]['children']]

In [162]:
find_wrong(a)

('vwkkml', [2090, 2090, 2090, 2090, 2096])

In [163]:
where_to_go(b4, 'vwkkml')

['kiatxq']

In [164]:
get_weight(b4, 'kiatxq')

2096

#8

In [80]:
lines = []

with open('prob8.txt', 'r') as prob_input:
    for line in prob_input:
        lines.append(line[:-1])

print(lines[:4], len(lines))

ex8 = lines

['sdj dec 558 if r <= 8', 'cpv inc 669 if csu >= -6', 'ke dec 312 if pep != 0', 'sdj inc -97 if bs == 0'] 1000


#part1

In [81]:
instr_list = [x.split() for x in ex8]
reg_list = [x[0] for x in instr_list]
regs = dict(zip(set(reg_list), [0]*len(set(reg_list))))

for i in instr_list:
    i_new = [x.replace('inc', '+').replace('dec', '-') for x in i]
    exec("regs['{0}'] = regs['{0}'] {1} {2} {3} regs['{4}'] {5} {6} else regs['{0}']".format(*i_new))

max(regs.values())

3880

#part2

In [82]:
instr_list = [x.split() for x in ex8]
reg_list = [x[0] for x in instr_list]
regs = dict(zip(set(reg_list), [0]*len(set(reg_list))))

max_sofar = 0

for i in instr_list:
    i_new = [x.replace('inc', '+').replace('dec', '-') for x in i]
    exec("regs['{0}'] = regs['{0}'] {1} {2} {3} regs['{4}'] {5} {6} else regs['{0}']".format(*i_new))
    max_sofar = max(max_sofar, max(regs.values()))

max_sofar

5035

#9

In [71]:
def get_input_by_lines(prob):
    lines = []

    with open('prob{}.txt'.format(prob), 'r') as prob_input:
        for line in prob_input:
            lines.append(line[:-1])

    #print(lines[:4], len(lines))

    return lines

In [88]:
def score_group(group):
    score = 0
    
    left_cnt = 0
    
    in_garbage = False
    ignore_next = False
    
    garbage_cnt = 0
    
    for idx, char in enumerate(group):
        #print(char)
        #print("in_garbage = {}".format(in_garbage))
        #print("ignore_next = {}".format(ignore_next))
        #print("left_cnt = {}".format(left_cnt))
        if in_garbage:
            if ignore_next:
                #print('in_garbage and ignore_next')
                ignore_next = False
                pass
            elif char == '>':
                #print('exiting garbage')
                in_garbage = False
            elif char == '!':
                #print('ignoring next')
                ignore_next = True
            else:
                garbage_cnt += 1
        elif char == '<':
            #print("entering garbage")
            in_garbage = True
        elif char == '{':
            #print("push \{ stack")
            left_cnt += 1
        elif char == '}':
            #print("pop \} stack")
            #print("add score {}".format(left_cnt))
            score += left_cnt
            left_cnt -= 1
        elif char == ',':
            #print("comma")
            pass
        else:
            pass
        #print("score: {}".format(score))
        
        #if idx < 50:
            #print(idx, score)
        #print()
        
    return score, garbage_cnt

In [4]:
ex = '{{{},{},{{}}}}'

In [5]:
score_group(ex)

16

In [26]:
ex2 = '{{<ab>},{<ab>},{<ab>},{<ab>}}'

In [29]:
score_group(ex2)

9

In [38]:
ex9 = get_input_by_lines(9)[0]

In [70]:
len(ex9)

28912

In [81]:
ex9[:50]

'{{},{{{{{},{{<!!!>!<"<!>,<!!!>!>},<!>,<\'e">},{<!!<'

In [89]:
score_group(ex9)

(21037, 9495)

#10

In [2]:
baselist = list(range(256))

In [43]:
def reverse_list(list0, start_idx, rev_len):
    list1 = list0.copy()
    
    end_idx = start_idx + rev_len - 1
    
    for idx in range(rev_len):
        idx1 = (end_idx - idx) % len(list0)
        idx0 = (start_idx + idx) % len(list0)
        list1[idx1] = list0[idx0]
    
    return list1

In [9]:
reverse_list(list(range(6)), 5, 3)

[0, 5, 2, 3, 4, 1]

In [11]:
baselist[:4]

[0, 1, 2, 3]

In [72]:
ex10 = [int(x) for x in get_input_by_lines(10)[0].split(',')]

In [73]:
ex10

[129, 154, 49, 198, 200, 133, 97, 254, 41, 6, 2, 1, 255, 0, 191, 108]

In [58]:
curr_idx = 0
skip_size = 0

mylist = baselist.copy()

for val in ex10:
    mylist = reverse_list(mylist, curr_idx, val)
    curr_idx += (val + skip_size)
    skip_size += 1

mylist[0] * mylist[1]

19591

In [1]:
ord(',')

44

In [6]:
base16 = np.array(baselist).reshape([-1, 16])

In [17]:
from functools import reduce


xor_arr = np.apply_along_axis((lambda x: reduce(np.bitwise_or, x)), axis=1, arr=base16)
[hex(x)[2:].rjust(2, '0') for x in xor_arr]

In [37]:
def asciify(str0):
    return [ord(x) for x in str0]

def asciify2(str0):
    list0 = asciify(str0)
    list0.extend([17, 31, 73, 47, 23])
    return list0

In [38]:
asciify2('1,2,3')

[49, 44, 50, 44, 51, 17, 31, 73, 47, 23]

In [39]:
def run_64(baselist, idces):
    curr_idx = 0
    skip_size = 0

    mylist = baselist.copy()

    for i in range(64):
        for val in idces:
            mylist = reverse_list(mylist, curr_idx, val)
            curr_idx += (val + skip_size)
            skip_size += 1

    return mylist

In [44]:
run_64(baselist, asciify2(''))

[38,
 171,
 116,
 63,
 70,
 137,
 168,
 29,
 198,
 55,
 160,
 15,
 34,
 95,
 58,
 7,
 188,
 189,
 238,
 141,
 30,
 31,
 124,
 241,
 20,
 1,
 244,
 203,
 234,
 73,
 236,
 211,
 122,
 197,
 94,
 227,
 142,
 57,
 72,
 239,
 54,
 81,
 154,
 217,
 10,
 13,
 186,
 161,
 6,
 17,
 128,
 105,
 106,
 69,
 44,
 51,
 248,
 23,
 136,
 173,
 52,
 39,
 40,
 5,
 254,
 195,
 64,
 187,
 192,
 37,
 230,
 153,
 56,
 177,
 84,
 147,
 96,
 249,
 252,
 121,
 166,
 143,
 62,
 169,
 90,
 99,
 196,
 155,
 132,
 159,
 162,
 229,
 76,
 117,
 164,
 127,
 150,
 21,
 88,
 27,
 242,
 67,
 114,
 115,
 226,
 191,
 190,
 53,
 2,
 65,
 206,
 205,
 24,
 251,
 14,
 75,
 74,
 247,
 80,
 11,
 50,
 181,
 46,
 101,
 100,
 179,
 48,
 131,
 32,
 97,
 102,
 201,
 170,
 93,
 104,
 103,
 182,
 125,
 12,
 43,
 220,
 113,
 158,
 167,
 68,
 47,
 66,
 33,
 112,
 135,
 194,
 185,
 218,
 219,
 8,
 245,
 130,
 253,
 204,
 243,
 202,
 109,
 92,
 209,
 156,
 133,
 250,
 107,
 4,
 183,
 60,
 215,
 172,
 231,
 240,
 83,
 98,
 193,
 82,
 139,


In [66]:
def run_hash(baselist):
    base16 = np.array(baselist).reshape([-1, 16])
    xor_arr = np.apply_along_axis((lambda x: reduce(np.bitwise_xor, x)), axis=1, arr=base16)
    print(xor_arr)
    return ''.join([hex(x)[2:].rjust(2, '0') for x in xor_arr])

In [61]:
np.apply_along_axis((lambda x: reduce(np.bitwise_or, x)), axis=1, arr=aa)

array([255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255,
       255, 255, 255])

In [67]:
run_hash(run_64(baselist, asciify2('')))

[162  88  42  58  14 102 230 232 110  56  18 220 182 114 162 114]


'a2582a3a0e66e6e86e3812dcb672a272'

In [76]:
ex10 = [str(x) for x in ex10]

In [79]:
as10 = ','.join(ex10)

In [80]:
run_hash(run_64(baselist, asciify2(as10)))

[ 98 226  32  77  44 164 244 146  79 110 122 128 241  40 135 134]


'62e2204d2ca4f4924f6e7a80f1288786'

#11


In [12]:
a, b, c = np.sign([2, -1, 0])

In [13]:
a, b, c

(1, -1, 0)

In [44]:
def simplify_coords(i, j, k):
    # i : n
    # j : se
    # k : sw
    
    # i + j + k -> 0
    while max(min(i, j), min(j, k), min(k, i)) > 0:
        i, j, k = i-1, j-1, k-1
    
    while min(max(i, j), max(j, k), max(k, i)) < 0:
        i, j, k = i+1, j+1, k+1

    return abs(i) + abs(j) + abs(k)

In [19]:
def get_input_by_lines(prob):
    lines = []

    with open('prob{}.txt'.format(prob), 'r') as prob_input:
        for line in prob_input:
            lines.append(line[:-1])

    #print(lines[:4], len(lines))

    return lines

In [29]:
ex11 = get_input_by_lines(11)[0].split(',')

In [32]:
len(ex11)

8223

In [46]:
def make_coords(dirs):
    max_d = 0
    i, j, k = 0, 0, 0
    n, s, se, nw, sw, ne = 0, 0, 0, 0, 0, 0
    
    for d in dirs:
        if d == 'n':
            i += 1
            n += 1
        elif d == 's':
            i -= 1
            s += 1
        elif d == 'se':
            j += 1
            se += 1
        elif d == 'nw':
            j -= 1
            nw += 1
        elif d == 'sw':
            k += 1
            sw += 1
        elif d == 'ne':
            k -= 1
            ne += 1
        
        cur_d = simplify_coords(i, j, k)
        if cur_d > max_d:
            max_d = cur_d
    
    return i, j, k, n, s, se, nw, sw, ne, max_d

In [47]:
make_coords(ex11)

(-367, -9, 429, 1330, 1697, 1330, 1339, 1478, 1049, 1585)

In [43]:
make_coords(ex11)[:3]

(-367, -9, 429)

In [45]:
simplify_coords(*make_coords(ex11)[:3])

796

#12

In [127]:
ex12 = get_input_by_lines(12)

In [128]:
ex12

['0 <-> 1352, 1864',
 '1 <-> 430',
 '2 <-> 1202, 1416',
 '3 <-> 303, 363, 635',
 '4 <-> 1041, 1383',
 '5 <-> 143, 1513',
 '6 <-> 6',
 '7 <-> 619',
 '8 <-> 167, 1246, 1822',
 '9 <-> 577, 1274, 1347',
 '10 <-> 10, 899',
 '11 <-> 790',
 '12 <-> 606',
 '13 <-> 1134, 1894',
 '14 <-> 539, 1974',
 '15 <-> 683, 1783',
 '16 <-> 438, 1235',
 '17 <-> 17',
 '18 <-> 760, 1162',
 '19 <-> 1146',
 '20 <-> 678, 1235, 1397, 1911',
 '21 <-> 127, 615, 980',
 '22 <-> 22, 187',
 '23 <-> 192, 552',
 '24 <-> 169',
 '25 <-> 471',
 '26 <-> 1030, 1329, 1333',
 '27 <-> 1404',
 '28 <-> 1249',
 '29 <-> 1755',
 '30 <-> 198',
 '31 <-> 510, 1884',
 '32 <-> 1088',
 '33 <-> 54, 372, 616, 938, 1548',
 '34 <-> 1574',
 '35 <-> 238, 1411',
 '36 <-> 114',
 '37 <-> 1962',
 '38 <-> 1554, 1633',
 '39 <-> 72, 486, 1002',
 '40 <-> 40, 1224, 1342, 1511, 1886',
 '41 <-> 1244, 1644',
 '42 <-> 1784',
 '43 <-> 169, 1142',
 '44 <-> 96, 827',
 '45 <-> 842, 1512',
 '46 <-> 1248',
 '47 <-> 283, 1125, 1130',
 '48 <-> 212, 327, 1922',
 '49 

In [85]:
a = '''0 <-> 2
1 <-> 1
2 <-> 0, 3, 4
3 <-> 2, 4
4 <-> 2, 3, 6
5 <-> 6
6 <-> 4, 5'''

In [132]:
def dictify12(ex12):
    outdict = dict()    
    #ex12 = ex12.split('\n')
    
    for line in ex12:
        #print(line)
        id_, connections = line.split(' <-> ')
        id_ = int(id_)
        connections = [int(x) for x in connections.split(', ')]
        outdict[id_] = connections
    return outdict

In [111]:
a[0]

'0'

In [112]:
aa = dictify12(a)

0 <-> 2
1 <-> 1
2 <-> 0, 3, 4
3 <-> 2, 4
4 <-> 2, 3, 6
5 <-> 6
6 <-> 4, 5


In [106]:
['a'].extend(['n'])

In [135]:
def get_nbrs(input_dict, id_, group_now):
    id_nbrs = input_dict[id_].copy()
    id_nbrs = [x for x in id_nbrs if x not in group_now]
    
    nbrs = []
    
    if not id_nbrs:
        nbrs.append(id_)
    else:
        nbrs.append(id_)
        for xx in id_nbrs:
            group_now.append(xx)
            nbrs.extend(get_nbrs(input_dict, xx, group_now))
    return set(nbrs)
        

In [125]:
get_nbrs(aa, 0, [])

2
0
3
4
6
5
4


{0, 2, 3, 4, 5, 6}

In [133]:
dictify12(ex12)

{0: [1352, 1864],
 1: [430],
 2: [1202, 1416],
 3: [303, 363, 635],
 4: [1041, 1383],
 5: [143, 1513],
 6: [6],
 7: [619],
 8: [167, 1246, 1822],
 9: [577, 1274, 1347],
 10: [10, 899],
 11: [790],
 12: [606],
 13: [1134, 1894],
 14: [539, 1974],
 15: [683, 1783],
 16: [438, 1235],
 17: [17],
 18: [760, 1162],
 19: [1146],
 20: [678, 1235, 1397, 1911],
 21: [127, 615, 980],
 22: [22, 187],
 23: [192, 552],
 24: [169],
 25: [471],
 26: [1030, 1329, 1333],
 27: [1404],
 28: [1249],
 29: [1755],
 30: [198],
 31: [510, 1884],
 32: [1088],
 33: [54, 372, 616, 938, 1548],
 34: [1574],
 35: [238, 1411],
 36: [114],
 37: [1962],
 38: [1554, 1633],
 39: [72, 486, 1002],
 40: [40, 1224, 1342, 1511, 1886],
 41: [1244, 1644],
 42: [1784],
 43: [169, 1142],
 44: [96, 827],
 45: [842, 1512],
 46: [1248],
 47: [283, 1125, 1130],
 48: [212, 327, 1922],
 49: [490],
 50: [359, 1386],
 51: [1186],
 52: [414],
 53: [808],
 54: [33, 673],
 55: [614],
 56: [56],
 57: [257],
 58: [482, 701, 1702, 1921],
 59: 

In [137]:
len(get_nbrs(dictify12(ex12), 0, []))

169

In [139]:
d12 = dictify12(ex12)


In [149]:
groups = []
for key in d12.keys():
    pass_ = False
    for g in groups:
        if key in g:
            pass_ = True
            
    if pass_:
        #print('pass')
        continue
    
    group = get_nbrs(d12, key, [])
    groups.append(group)
    

    

In [145]:
groups

[{0,
  3,
  11,
  12,
  13,
  21,
  28,
  71,
  98,
  108,
  127,
  136,
  150,
  153,
  157,
  163,
  172,
  174,
  185,
  239,
  244,
  245,
  251,
  253,
  256,
  273,
  278,
  301,
  303,
  315,
  337,
  346,
  363,
  392,
  398,
  405,
  421,
  431,
  447,
  449,
  454,
  456,
  467,
  476,
  485,
  491,
  511,
  518,
  521,
  536,
  542,
  556,
  560,
  586,
  593,
  606,
  609,
  615,
  625,
  633,
  635,
  641,
  648,
  671,
  675,
  680,
  696,
  715,
  716,
  720,
  722,
  731,
  734,
  738,
  740,
  755,
  759,
  790,
  794,
  800,
  803,
  823,
  910,
  946,
  975,
  980,
  982,
  1001,
  1035,
  1053,
  1060,
  1124,
  1129,
  1134,
  1144,
  1149,
  1156,
  1185,
  1195,
  1197,
  1201,
  1214,
  1217,
  1231,
  1239,
  1249,
  1277,
  1280,
  1282,
  1283,
  1300,
  1304,
  1322,
  1339,
  1343,
  1352,
  1353,
  1365,
  1368,
  1369,
  1372,
  1408,
  1422,
  1433,
  1467,
  1468,
  1473,
  1484,
  1496,
  1503,
  1532,
  1534,
  1546,
  1547,
  1569,
  1572,
  1581,
  

In [150]:
len(groups)

179

In [151]:
x = 4

In [152]:
def aaa(z):
    return x

In [153]:
aaa(0)

4

#13

In [3]:
ex13_0 = get_input_by_lines(13)

In [ ]:
{0: {'pos': 0, 'dir': 'up', 'range_': 4}}

In [91]:
def init_stack(ex13):
    dict0 = dict()
    
    for line in ex13:
        idx, range_ = line.split(': ')
        idx, range_ = int(idx), int(range_)
        dict0[idx] = {'pos': 0, 'dir_': 'd',
                      'range_': range_}
    
    return dict0

In [78]:
ex13 = init_stack(ex13_0)

In [17]:
ex13

{0: {'dir_': 'd', 'pos': 0, 'range_': 4},
 1: {'dir_': 'd', 'pos': 0, 'range_': 2},
 2: {'dir_': 'd', 'pos': 0, 'range_': 3},
 4: {'dir_': 'd', 'pos': 0, 'range_': 4},
 6: {'dir_': 'd', 'pos': 0, 'range_': 8},
 8: {'dir_': 'd', 'pos': 0, 'range_': 5},
 10: {'dir_': 'd', 'pos': 0, 'range_': 6},
 12: {'dir_': 'd', 'pos': 0, 'range_': 6},
 14: {'dir_': 'd', 'pos': 0, 'range_': 10},
 16: {'dir_': 'd', 'pos': 0, 'range_': 8},
 18: {'dir_': 'd', 'pos': 0, 'range_': 6},
 20: {'dir_': 'd', 'pos': 0, 'range_': 9},
 22: {'dir_': 'd', 'pos': 0, 'range_': 8},
 24: {'dir_': 'd', 'pos': 0, 'range_': 6},
 26: {'dir_': 'd', 'pos': 0, 'range_': 8},
 28: {'dir_': 'd', 'pos': 0, 'range_': 8},
 30: {'dir_': 'd', 'pos': 0, 'range_': 12},
 32: {'dir_': 'd', 'pos': 0, 'range_': 12},
 34: {'dir_': 'd', 'pos': 0, 'range_': 12},
 36: {'dir_': 'd', 'pos': 0, 'range_': 12},
 38: {'dir_': 'd', 'pos': 0, 'range_': 10},
 40: {'dir_': 'd', 'pos': 0, 'range_': 12},
 42: {'dir_': 'd', 'pos': 0, 'range_': 12},
 44: {'di

In [19]:
ex13[0][]

{'dir_': 'd', 'pos': 0, 'range_': 4}

In [90]:
def adv_time(ex13):
    for key in ex13.keys():
        if ex13[key]['dir_'] == 'd':
            ex13[key]['pos'] += 1
            if ex13[key]['pos'] >= ex13[key]['range_']-1:
                ex13[key]['dir_'] = 'u'
        elif ex13[key]['dir_'] == 'u':
            ex13[key]['pos'] -= 1
            if ex13[key]['pos'] <= 0:
                ex13[key]['dir_'] = 'd'
    return ex13

In [79]:
k = 0

In [89]:
k += 1
k, adv_time(ex13)

(10,
 {0: {'dir_': 'd', 'pos': 2, 'range_': 4},
  1: {'dir_': 'u', 'pos': 2, 'range_': 2},
  2: {'dir_': 'u', 'pos': 2, 'range_': 3},
  4: {'dir_': 'd', 'pos': 2, 'range_': 4},
  6: {'dir_': 'u', 'pos': 6, 'range_': 8},
  8: {'dir_': 'd', 'pos': 0, 'range_': 5},
  10: {'dir_': 'u', 'pos': 2, 'range_': 6},
  12: {'dir_': 'u', 'pos': 2, 'range_': 6},
  14: {'dir_': 'u', 'pos': 10, 'range_': 10},
  16: {'dir_': 'u', 'pos': 6, 'range_': 8},
  18: {'dir_': 'u', 'pos': 2, 'range_': 6},
  20: {'dir_': 'u', 'pos': 8, 'range_': 9},
  22: {'dir_': 'u', 'pos': 6, 'range_': 8},
  24: {'dir_': 'u', 'pos': 2, 'range_': 6},
  26: {'dir_': 'u', 'pos': 6, 'range_': 8},
  28: {'dir_': 'u', 'pos': 6, 'range_': 8},
  30: {'dir_': 'd', 'pos': 10, 'range_': 12},
  32: {'dir_': 'd', 'pos': 10, 'range_': 12},
  34: {'dir_': 'd', 'pos': 10, 'range_': 12},
  36: {'dir_': 'd', 'pos': 10, 'range_': 12},
  38: {'dir_': 'u', 'pos': 10, 'range_': 10},
  40: {'dir_': 'd', 'pos': 10, 'range_': 12},
  42: {'dir_': 'd',

In [97]:
def run_13(ex13):
    curr = -1
    end = max(ex13.keys())
    sev = 0
    
    while curr <= end:
        curr += 1
        
        if curr in ex13.keys() and ex13[curr]['pos'] == 0:
            #print(curr)
            #print(ex13)
            sev += ex13[curr]['range_'] * curr

        ex13 = adv_time(ex13)
    #print(end)
    return sev

In [94]:
run_13(init_stack(ex13_0))

0
8
10
28
52
66
98


1844

In [98]:
def find_delay(ex13):
    base = ex13.copy()
    
    for delay in range(2000):
        ex13 = base.copy()
        for i in range(delay):
            ex13 = adv_time(ex13)
        sev = run_13(ex13)
        if sev == 0:
            print(delay)

In [150]:
def run_132(ex13, delay):
    curr = -1
    end = max(ex13.keys())
    sev = 0
    
    for i in range(delay):
        ex13 = adv_time(ex13)
    
    while curr <= end:
        curr += 1
        
        if curr in ex13.keys() and ex13[curr]['pos'] == 0:
            print(curr)
            #print(curr)
            #print(ex13)
            sev += ex13[curr]['range_'] * curr

        ex13 = adv_time(ex13)
    #print(end)
    return sev

In [151]:
run_132(ex130, 3)

1


2

In [104]:
find_delay(ex130)

In [155]:
ex130 = init_stack(ex13_0)

In [118]:
for i in range(20000):
    if i%100 == 0:
        print(i, end=' ')
    ex130 = init_stack(ex13_0)
    sev = run_132(ex130, i)
    if sev == 0:
        print('{}<------ HERE'.format(i), end='')
        

0 100 200 300 400 500 600 700 800 900 1000 1100 1200 1300 1400 1500 1600 1700 1800 1900 2000 2100 2200 2300 2400 2500 2600 2700 2800 2900 3000 3100 3200 3300 3400 3500 3600 3700 3800 3900 4000 4100 4200 4300 4400 4500 4600 4700 4800 4900 5000 5100 5200 5300 5400 5500 5600 5700 5800 5900 6000 6100 6200 6300 6400 6500 6600 6700 6800 6900 7000 7100 7200 7300 7400 7500 7600 7700 7800 7900 

KeyboardInterrupt: 

In [159]:
yy = [(x, 2*ex130[x]['range_']-2) for x in ex130.keys()]

In [165]:
np.array(yy)[:, 1]

array([ 6,  2,  4,  6, 14,  8, 10, 10, 18, 14, 10, 16, 14, 10, 14, 14, 22,
       22, 22, 22, 18, 22, 22, 26, 14, 26, 22, 26, 26, 26, 22, 26, 26, 22,
       22, 26, 34, 32, 26, 38, 26, 26, 34, 34])

In [170]:
for i in range(1, 2000000):
    if i % 10000 == 0:
        print(i, end=' ')
    rr = np.array(yy)[:, 0] + i
    if (rr % np.array(yy)[:, 1]).min() > 0:
        print(i)

10000 20000 30000 40000 50000 60000 70000 80000 90000 100000 110000 120000 130000 140000 150000 160000 170000 180000 190000 200000 210000 220000 230000 240000 250000 260000 270000 280000 290000 300000 310000 320000 330000 340000 350000 360000 370000 380000 390000 400000 410000 420000 430000 440000 450000 460000 470000 480000 490000 500000 510000 520000 530000 540000 550000 560000 570000 580000 590000 600000 610000 620000 630000 640000 650000 660000 670000 680000 690000 700000 710000 720000 730000 740000 750000 760000 770000 780000 790000 800000 810000 820000 830000 840000 850000 860000 870000 880000 890000 900000 910000 920000 930000 940000 950000 960000 970000 980000 990000 1000000 1010000 1020000 1030000 1040000 1050000 1060000 1070000 1080000 1090000 1100000 1110000 1120000 1130000 1140000 1150000 1160000 1170000 1180000 1190000 1200000 1210000 1220000 1230000 1240000 1250000 1260000 1270000 1280000 1290000 1300000 1310000 1320000 1330000 1340000 1350000 1360000 1370000 1380000 1390

In [172]:
for i in range(2000000, 20000000):
    if i % 100000 == 0:
        print(i, end=' ')
    rr = np.array(yy)[:, 0] + i
    if (rr % np.array(yy)[:, 1]).min() > 0:
        print(i)

2000000 2100000 2200000 2300000 2400000 2500000 2600000 2700000 2800000 2900000 3000000 3100000 3200000 3300000 3400000 3500000 3600000 3700000 3800000 3897604
3900000 4000000 4100000 4119364
4200000 4300000 4400000 4500000 4600000 4700000 4800000 4900000 5000000 5100000 5200000 5300000 5339044
5400000 5500000 5560804
5600000 5700000 5800000 5900000 6000000 6100000 6200000 6300000 6400000 6500000 6600000 6700000 6780484
6800000 6900000 7000000 7002244
7100000 7200000 7300000 7400000 7500000 7600000 7700000 7800000 7900000 8000000 8100000 8200000 8221924
8300000 8400000 8443684
8500000 8600000 8700000 8800000 8900000 9000000 9100000 9200000 

KeyboardInterrupt: 

In [4]:
ex13_0

['0: 4',
 '1: 2',
 '2: 3',
 '4: 4',
 '6: 8',
 '8: 5',
 '10: 6',
 '12: 6',
 '14: 10',
 '16: 8',
 '18: 6',
 '20: 9',
 '22: 8',
 '24: 6',
 '26: 8',
 '28: 8',
 '30: 12',
 '32: 12',
 '34: 12',
 '36: 12',
 '38: 10',
 '40: 12',
 '42: 12',
 '44: 14',
 '46: 8',
 '48: 14',
 '50: 12',
 '52: 14',
 '54: 14',
 '58: 14',
 '60: 12',
 '62: 14',
 '64: 14',
 '66: 12',
 '68: 12',
 '72: 14',
 '74: 18',
 '76: 17',
 '86: 14',
 '88: 20',
 '92: 14',
 '94: 14',
 '96: 18',
 '98: 18']

#14

In [6]:
baselist = list(range(256))
base16 = np.array(baselist).reshape([-1, 16])

In [22]:
from functools import reduce

def reverse_list(list0, start_idx, rev_len):
    list1 = list0.copy()
    
    end_idx = start_idx + rev_len - 1
    
    for idx in range(rev_len):
        idx1 = (end_idx - idx) % len(list0)
        idx0 = (start_idx + idx) % len(list0)
        list1[idx1] = list0[idx0]
    
    return list1

def asciify(str0):
    return [ord(x) for x in str0]

def asciify2(str0):
    list0 = asciify(str0)
    list0.extend([17, 31, 73, 47, 23])
    return list0

def run_64(baselist, idces):
    curr_idx = 0
    skip_size = 0

    mylist = baselist.copy()

    for i in range(64):
        for val in idces:
            mylist = reverse_list(mylist, curr_idx, val)
            curr_idx += (val + skip_size)
            skip_size += 1

    return mylist

def run_hash(baselist):
    base16 = np.array(baselist).reshape([-1, 16])
    xor_arr = np.apply_along_axis((lambda x: reduce(np.bitwise_xor, x)), axis=1, arr=base16)
    #print(xor_arr)
    return ''.join([hex(x)[2:].rjust(2, '0') for x in xor_arr])

def knot_hash(baselist, str0):
    return run_hash(run_64(baselist, asciify2(str0)))

def hash_row(baselist, str0):
    return '{:0>128}'.format(str(bin(int(knot_hash(baselist, str0), 16)))[2:])

In [27]:
np.array(list(hash_row(baselist, 'hxtvlmkl-0'))).astype(np.int32)

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0], dtype=int32)

In [28]:
used = 0
base_str = 'hxtvlmkl'

for i in range(128):
    used += ((np.array(list(hash_row(baselist, '{0}-{1}'.format(base_str, i)))).astype(np.int32))==1).sum()
    
print(used)

8214


In [172]:
grid = []

for i in range(128):
    grid.extend(int(x) for x in list(hash_row(baselist, '{0}-{1}'.format(base_str, i))))

ndgrid = np.array(grid).reshape(128, 128)

ndgrid[:9, :9]

array([[0, 0, 0, 1, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 1, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 1, 1, 1, 0]])

In [169]:
def fill_region(row, col):#, fill_value=None):
    global ndgrid, regions, region_count, ROWS, COLS

    #print('filling {}, {}, with {}'.format(row, col, region_count))

    up = (max(0, row-1), col)
    down = (min(ROWS-1, row+1), col)
    left = (row, max(0, col-1))
    right = (row, min(COLS-1, col+1))
    #print(down, left, right)
    regions[row, col] = region_count
    #print(row, col)
#     if (row, col) == (ROWS-1, 0) or (row, col) == (ROWS-1, COLS-1):
#         return
    
    filled_any = False
    for neighbor in [right, down, left, up]:
        if neighbor != (row, col) and ndgrid[neighbor] != 0\
        and regions[neighbor] == 0:
            fill_region(*neighbor)
            filled_any = True
        else:
            pass
    return

In [171]:
ROWS, COLS = ndgrid.shape

region_count = 0
regions = np.zeros((ROWS, COLS))

for row in range(ROWS):
    for col in range(COLS):
        if ndgrid[row, col] == 1:
            up = (max(0, row-1), col)
            down = (min(ROWS-1, row+1), col)
            left = (row, max(0, col-1))
            right = (row, min(COLS-1, col+1))
            #print(up, down, left, right)
            if regions[row, col] != 0:
                pass
            else:
                region_count += 1
                fill_region(row, col)
                
            
        else:
            continue

print(region_count)

1093


In [173]:
regions[:9, :9]

array([[   0.,    0.,    0.,    1.,    0.,    2.,    2.,    0.,    0.],
       [  31.,   31.,    0.,    0.,   32.,    0.,    0.,    0.,    0.],
       [  31.,    0.,    0.,   43.,    0.,   43.,   43.,   43.,    0.],
       [   0.,   43.,   43.,   43.,    0.,    0.,   43.,    0.,   43.],
       [   0.,   43.,    0.,   43.,   43.,   43.,   43.,   43.,   43.],
       [  43.,   43.,    0.,   43.,    0.,   43.,   43.,   43.,   43.],
       [   0.,    0.,    0.,    0.,    0.,   43.,    0.,   43.,    0.],
       [   0.,    0.,   95.,    0.,   96.,    0.,    0.,    0.,   43.],
       [  95.,    0.,   95.,    0.,    0.,  105.,  105.,  105.,    0.]])

past tests

In [174]:
ndgrid = np.array([[1, 0, 0, 0, 0, 1, 0, 0],
                   [1, 1, 1, 1, 1, 1, 0, 1],
                   [0, 0, 0, 0, 0, 0, 1, 1],
                   [0, 0, 0, 1, 0, 0, 0, 1],
                   [0, 1, 1, 1, 1, 0, 1, 1],
                   [1, 0, 0, 0, 1, 1, 1, 1]])

ndgrid

array([[1, 0, 0, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 0, 1, 1, 1, 1]])

In [167]:
regions

array([[ 1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  0.,  2.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  2.,  2.],
       [ 0.,  0.,  0.,  2.,  0.,  0.,  0.,  2.],
       [ 0.,  2.,  2.,  2.,  2.,  0.,  2.,  2.],
       [ 3.,  0.,  0.,  0.,  2.,  2.,  2.,  2.]])

# 15


In [88]:
a00, b00 = 65, 8921

In [89]:
a0 = 634
b0 = 301
afac = 16807
bfac = 48271
n = 2**31 - 1

In [90]:
def bit16(int0):
    return '{:0>32}'.format(str(bin(int0))[2:])[-16:]

15-1

In [92]:
%%time
count = 0

a = a0
b = b0

for it in range(400000):
    a = a*afac % n
    b = b*bfac % n
    #print(a, b)
    if bit16(a) == bit16(b):
        count += 1
print(count)

8
CPU times: user 776 ms, sys: 0 ns, total: 776 ms
Wall time: 773 ms


15-2

In [93]:
adiv = 4
bdiv = 8

In [87]:
%%time
count = 0

a = a0
b = b0

for it in range(5000000):
    while a % adiv:
        a = a*afac % n
    while b % bdiv:
        b = b*bfac % n

    if bit16(a) == bit16(b):
        count += 1
    
    a = a*afac % n
    b = b*bfac % n
    
    if it % 10000 == 0:
        print(it, end=' ')
print(count)

0 10000 20000 30000 40000 50000 60000 70000 80000 90000 100000 110000 120000 130000 140000 150000 160000 170000 180000 190000 200000 210000 220000 230000 240000 250000 260000 270000 280000 290000 300000 310000 320000 330000 340000 350000 360000 370000 380000 390000 400000 410000 420000 430000 440000 450000 460000 470000 480000 490000 500000 510000 520000 530000 540000 550000 560000 570000 580000 590000 600000 610000 620000 630000 640000 650000 660000 670000 680000 690000 700000 710000 720000 730000 740000 750000 760000 770000 780000 790000 800000 810000 820000 830000 840000 850000 860000 870000 880000 890000 900000 910000 920000 930000 940000 950000 960000 970000 980000 990000 1000000 1010000 1020000 1030000 1040000 1050000 1060000 1070000 1080000 1090000 1100000 1110000 1120000 1130000 1140000 1150000 1160000 1170000 1180000 1190000 1200000 1210000 1220000 1230000 1240000 1250000 1260000 1270000 1280000 1290000 1300000 1310000 1320000 1330000 1340000 1350000 1360000 1370000 1380000 13

# 16